AutoPedia/AutoPedia/urls.py
from django.contrib import admin
from django.urls import path, include
from autos.views import home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", home, name="home"),
    path("admin/", admin.site.urls),
    path("marcas/", include("marcas.urls")),
    path("autos/", include("autos.urls")),
    path("usuarios/", include("usuarios.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AutoPedia/autos/urls.py
# autos/urls.py
from django.urls import path
from .views import *

app_name = "autos"

urlpatterns = [
    path("", home, name="home"),
    path("modelos/", ListaModelos.as_view(), name="lista_modelos"),
    path("modelos/crear/", crear_modelo, name="crear_modelo"),
    path("modelos/<int:pk>/", DetalleModelo.as_view(), name="detalle_modelo"),
    path("modelos/editar/<int:pk>/", editar_modelo, name="editar_modelo"),
    path("modelos/eliminar/<int:pk>/", eliminar_modelo, name="eliminar_modelo"),
    path("buscar_resultados/", buscar_resultados, name="buscar_resultados"),
]

AutoPedia/marcas/urls.py
# marcas/urls.py
from django.urls import path
from .views import ListaMarcas, DetalleMarca, crear_marca, editar_marca, eliminar_marca

app_name = "marcas"

urlpatterns = [
    path("lista_marcas/", ListaMarcas.as_view(), name="lista_marcas"),
    path("detalle_marca/<int:pk>/", DetalleMarca.as_view(), name="detalle_marca"),
    path("crear_marca/", crear_marca, name="crear_marca"),
    path("editar_marca/<int:pk>/", editar_marca, name="editar_marca"),
    path("eliminar_marca/<int:pk>/", eliminar_marca, name="eliminar_marca"),
]

AutoPedia/marcas/models.py
# marcas/models.py
from django.db import models


class Marca(models.Model):
    nombre = models.CharField(max_length=100)
    logo = models.ImageField(upload_to="marcas/logos/")
    año_fundación = models.PositiveIntegerField()
    pais_origen = models.CharField(max_length=50)
    descripcion = models.TextField()
    fundador = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.nombre

AutoPedia/marcas/forms.py
# marcas/forms.py
from django import forms
from .models import Marca


class MarcaForm(forms.ModelForm):
    class Meta:
        model = Marca
        fields = [
            "nombre",
            "logo",
            "año_fundación",
            "pais_origen",
            "descripcion",
            "fundador",
        ]

    # Indicar que los campos no son obligatorios
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = False

AutoPedia/marcas/views.py
# marcas/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .models import Marca
from .forms import MarcaForm


class ListaMarcas(ListView):
    model = Marca
    template_name = "marcas/lista_marcas.html"
    context_object_name = "marcas"


class DetalleMarca(DetailView):
    model = Marca
    template_name = "marcas/detalle_marca.html"
    context_object_name = "marca"


@staff_member_required
def crear_marca(request):
    if request.method == "POST":
        form = MarcaForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("marcas:lista_marcas")
    else:
        form = MarcaForm()
    return render(request, "marcas/formulario_marca.html", {"form": form})


@staff_member_required
def editar_marca(request, pk):
    marca = get_object_or_404(Marca, pk=pk)
    if request.method == "POST":
        form = MarcaForm(request.POST, request.FILES, instance=marca)
        if form.is_valid():
            form.save()
            return redirect("marcas:lista_marcas")
    else:
        form = MarcaForm(instance=marca)
    return render(request, "marcas/formulario_marca.html", {"form": form})


@staff_member_required
def eliminar_marca(request, pk):
    marca = get_object_or_404(Marca, pk=pk)
    marca.delete()
    return redirect("marcas:lista_marcas")

AutoPedia/templates/marcas/detalle_marca.html
<!-- marcas/templates/marcas/detalle_marca.html -->
{% extends 'base/base.html' %}

{% block content %}
<div class="container mt-4">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <h1 class="card-title">{{ marca.nombre }}</h1>
                    <p class="card-text"><strong>Año de Fundación:</strong> {{ marca.año_fundación }}</p>
                    <p class="card-text"><strong>País de Origen:</strong> {{ marca.pais_origen }}</p>
                    <p class="card-text"><strong>Fundador:</strong> {{ marca.fundador }}</p>
                </div>
                <div class="col-md-6 text-center">
                    <img src="{{ marca.logo.url }}" alt="{{ marca.nombre }} Logo" class="img-fluid mb-3"
                        style="max-width: 200px;">
                </div>
            </div>
            <p class="card-text"><strong>Descripción:</strong> {{ marca.descripcion }}</p>
            <!-- Puedes agregar más detalles según tus necesidades -->
        </div>
    </div>
</div>
{% endblock %}

AutoPedia/templates/marcas/formulario_marca.html
<!-- marcas/templates/marcas/formulario_marca.html -->
{% extends "base/base.html" %}

{% block content %}
<h1>{% if form.instance.pk %}Editar{% else %}Crear{% endif %} Marca</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
</form>
<a href="{% url 'marcas:lista_marcas' %}">Volver a la lista de marcas</a>
{% endblock %}

AutoPedia/templates/marcas/lista_marcas.html
<!-- marcas/templates/marcas/lista_marcas.html -->
{% extends "base/base.html" %}
{% load static %}

{% block content %}
<style>
    .card {
        width: 15rem;
        /* Puedes ajustar el ancho según tus necesidades */
        margin-bottom: 20px;
        /* Espaciado entre tarjetas */
    }

    .card-img-top {
        height: 150px;
        /* Puedes ajustar la altura según tus necesidades */
        object-fit: contain;
        /* Ajusta el tamaño de la imagen manteniendo la proporción */
    }

    .card-title {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }
</style>

<div class="container mt-4">
    <h1 class="mb-4">Lista de Marcas</h1>
    {% if user.is_superuser %}
    <a href="{% url 'marcas:crear_marca' %}" class="btn btn-primary mb-3">Agregar nueva marca</a>
    {% endif %}

    <div class="row">
        {% for marca in marcas %}
        <div class="col-md-4">
            <div class="card">
                <a href="{% url 'marcas:detalle_marca' pk=marca.pk %}">
                    <img src="{{ marca.logo.url }}" alt="{{ marca.nombre }} Logo" class="card-img-top img-fluid">
                </a>
            </div>
        </div>
        {% endfor %} 
    </div>
</div>
{% endblock %}