AutoPedia/AutoPedia/urls.py
from django.contrib import admin
from django.urls import path, include
from autos.views import home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", home, name="home"),
    path("admin/", admin.site.urls),
    path("marcas/", include("marcas.urls")),
    path("autos/", include("autos.urls")),
    path("usuarios/", include("usuarios.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AutoPedia/autos/urls.py
# autos/urls.py
from django.urls import path
from .views import *

app_name = "autos"

urlpatterns = [
    path("", home, name="home"),
    path("modelos/", ListaModelos.as_view(), name="lista_modelos"),
    path("modelos/crear/", crear_modelo, name="crear_modelo"),
    path("modelos/<int:pk>/", DetalleModelo.as_view(), name="detalle_modelo"),
    path("modelos/editar/<int:pk>/", editar_modelo, name="editar_modelo"),
    path("modelos/eliminar/<int:pk>/", eliminar_modelo, name="eliminar_modelo"),
    path("buscar_resultados/", buscar_resultados, name="buscar_resultados"),
]

AutoPedia/marcas/urls.py
# marcas/urls.py
from django.urls import path
from .views import ListaMarcas, DetalleMarca, crear_marca, editar_marca, eliminar_marca

app_name = "marcas"

urlpatterns = [
    path("lista_marcas/", ListaMarcas.as_view(), name="lista_marcas"),
    path("detalle_marca/<int:pk>/", DetalleMarca.as_view(), name="detalle_marca"),
    path("crear_marca/", crear_marca, name="crear_marca"),
    path("editar_marca/<int:pk>/", editar_marca, name="editar_marca"),
    path("eliminar_marca/<int:pk>/", eliminar_marca, name="eliminar_marca"),
]

AutoPedia/autos/models.py
from django.db import models
from marcas.models import Marca


class Modelo(models.Model):
    nombre = models.CharField(max_length=100)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    generacion = models.CharField(max_length=20, null=True)
    año_inicio = models.PositiveIntegerField(null=True)
    año_fin = models.PositiveIntegerField(null=True, blank=True)
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to="autos/images/")
    cilindrada_motor_litros = models.DecimalField(
        max_digits=4, decimal_places=1, null=True, blank=True
    )
    caballos_fuerza = models.PositiveIntegerField(null=True, blank=True)
    torque = models.PositiveIntegerField(null=True, blank=True)
    configuracion_motor = models.CharField(max_length=50, null=True, blank=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)  # Agrega este campo

    def __str__(self):
        return f"{self.marca} - {self.nombre} ({self.año_inicio}-{self.año_fin})"

AutoPedia/autos/forms.py
# autos/forms.py
from django import forms
from .models import Marca, Modelo


class MarcaForm(forms.ModelForm):
    class Meta:
        model = Marca
        fields = ["nombre"]


class ModeloForm(forms.ModelForm):
    class Meta:
        model = Modelo
        fields = [
            "nombre",
            "marca",
            "generacion",
            "año_inicio",
            "año_fin",
            "descripcion",
            "imagen",
            "cilindrada_motor_litros",
            "caballos_fuerza",
            "torque",
            "configuracion_motor",
        ]

AutoPedia/autos/views.py
# autos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic import ListView, DetailView
from .models import Modelo
from .forms import ModeloForm
from marcas.models import Marca


def home(request):
    ultimos_modelos = Modelo.objects.order_by("-fecha_creacion")[:3]
    return render(request, "home/home.html", {"ultimos_modelos": ultimos_modelos})


@staff_member_required
def crear_modelo(request):
    if request.method == "POST":
        form = ModeloForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("autos:lista_modelos")
    else:
        form = ModeloForm()
    return render(request, "autos/formulario_modelo.html", {"form": form})


class ListaModelos(ListView):
    model = Modelo
    template_name = "autos/lista_modelos.html"
    context_object_name = "modelos"


class DetalleModelo(DetailView):
    model = Modelo
    template_name = "autos/detalle_modelo.html"
    context_object_name = "modelo"


@staff_member_required
def editar_modelo(request, pk):
    modelo = get_object_or_404(Modelo, pk=pk)
    if request.method == "POST":
        form = ModeloForm(request.POST, request.FILES, instance=modelo)
        if form.is_valid():
            form.save()
            return redirect("autos:lista_modelos")
    else:
        form = ModeloForm(instance=modelo)
    return render(request, "autos/formulario_modelo.html", {"form": form})


@staff_member_required
def eliminar_modelo(request, pk):
    modelo = get_object_or_404(Modelo, pk=pk)
    modelo.delete()
    return redirect("autos:lista_modelos")


def buscar_resultados(request):
    query = request.GET.get("q")
    resultados_autos = Modelo.objects.filter(nombre__icontains=query)
    resultados_marcas = Marca.objects.filter(nombre__icontains=query)

    return render(
        request,
        "autos/buscar_resultados.html",
        {"resultados_autos": resultados_autos, "resultados_marcas": resultados_marcas},
    )

AutoPedia/templates/autos/buscar_resultados.html
<!-- buscar_resultados.html -->
{% extends 'base/base.html' %}

{% block content %}
<h2>Resultados de la búsqueda para "{{ request.GET.q }}"</h2>

<h3>Autos</h3>
<ul>
    {% for auto in resultados_autos %}
    <li><a href="{% url 'autos:detalle_modelo' pk=auto.pk %}">{{ auto.nombre }}</a></li>
    {% endfor %}
</ul>

<h3>Marcas</h3>
<ul>
    {% for marca in resultados_marcas %}
    <li><a href="{% url 'marcas:detalle_marca' pk=marca.pk %}">{{ marca.nombre }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

AutoPedia/templates/autos/detalle_modelo.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container mt-4">
    <div class="card">
        <div class="card-body">
            <strong>
                <h1 class="card-title">{{ modelo.marca.nombre }} - {{ modelo.nombre }}</h1>
            </strong>
            <p class="card-text"><strong>Año de Inicio:</strong> {{ modelo.año_inicio }}</p>
            <p class="card-text"><strong>Año de Fin:</strong> {{ modelo.año_fin }}</p>
            <p class="card-text"><strong>Descripción:</strong> {{ modelo.descripcion }}</p>
            <p class="card-text"><strong>Cilindrada del Motor:</strong> {{ modelo.cilindrada_motor_litros }}L</p>
            <p class="card-text"><strong>Configuración del Motor:</strong> {{ modelo.configuracion_motor }}</p>

            <!-- Agrega la imagen del auto -->
            {% if modelo.imagen %}
            <img src="{{ modelo.imagen.url }}" alt="{{ modelo.nombre }} - Imagen" class="img-fluid mt-3">
            {% endif %}

            <!-- Puedes agregar más detalles según tus necesidades -->
        </div>
    </div>
</div>
{% endblock %}

AutoPedia/templates/autos/formulario_modelo.html
{% extends 'base/base.html' %}

{% block content %}
<!-- Aquí va el contenido específico de la plantilla formulario_modelo.html -->
<h1>{% if form.instance.pk %}Editar{% else %}Crear{% endif %} Modelo</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <!-- Agregar el campo de marca -->
    <label for="{{ form.marca.id_for_label }}">Marca:</label>
    {{ form.marca }}
    <br>

    <button type="submit">Guardar</button>
</form>
<a href="{% url 'autos:lista_modelos' %}">Volver a la lista de modelos</a>
{% endblock %}

AutoPedia/templates/autos/lista_modelos.html
<!-- autos/templates/autos/lista_modelos.html -->
{% extends 'base/base.html' %}

{% block content %}
<style>
    .card {
        width: 14rem;
        /* Puedes ajustar el ancho según tus necesidades */
        margin-bottom: 20px;
        /* Espaciado entre tarjetas */
    }

    .card-img-top {
        object-fit: cover;
        /* Ajusta el tamaño de la imagen manteniendo la proporción */
        border-top-left-radius: 10px;
        /* Bordes redondeados en la parte superior izquierda */
        border-top-right-radius: 10px;
        /* Bordes redondeados en la parte superior derecha */
        height: 100%;
        /* Hace que la imagen llene completamente la tarjeta en la parte superior */
        width: 100%;
        /* Hace que la imagen llene completamente la tarjeta en la parte superior */
    }

    .card-title {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }

    .card-text {
        flex-grow: 1;
        /* Hace que el contenido se expanda para llenar el espacio disponible */
    }
</style>

<div class="container mt-4">
    <h1 class="mb-4">Lista de Modelos de Autos</h1>
    {% if user.is_superuser %}
    <a href="{% url 'autos:crear_modelo' %}" class="btn btn-primary mb-3">Agregar nuevo modelo</a>
    {% endif %}

    <div class="row">
        {% for modelo in modelos %}
        <div class="col-md-4">
            <div class="card d-flex flex-column justify-content-between">
                <img src="{{ modelo.imagen.url }}" alt="{{ modelo.nombre }} - Imagen"
                    class="card-img-top img-fluid rounded-top">
                <div class="card-body text-center">
                    <h6 class="card-title">{{ modelo.nombre }}</h6>
                    <p class="card-text">{{ modelo.marca }} - {{ modelo.generacion }} - {{ modelo.año_inicio }} - {{modelo.año_fin }}</p>
                    <a href="{% url 'autos:detalle_modelo' pk=modelo.pk %}" class="btn btn-primary btn-sm">Ver
                        Detalles</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}