AutoPedia/AutoPedia/urls.py
from django.contrib import admin
from django.urls import path, include
from autos.views import home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", home, name="home"),
    path("admin/", admin.site.urls),
    path("marcas/", include("marcas.urls")),
    path("autos/", include("autos.urls")),
    path("usuarios/", include("usuarios.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AutoPedia/autos/urls.py
# autos/urls.py
from django.urls import path
from .views import *

app_name = "autos"

urlpatterns = [
    path("", home, name="home"),
    path("modelos/", ListaModelos.as_view(), name="lista_modelos"),
    path("modelos/crear/", crear_modelo, name="crear_modelo"),
    path("modelos/<int:pk>/", DetalleModelo.as_view(), name="detalle_modelo"),
    path("modelos/editar/<int:pk>/", editar_modelo, name="editar_modelo"),
    path("modelos/eliminar/<int:pk>/", eliminar_modelo, name="eliminar_modelo"),
    path("buscar_resultados/", buscar_resultados, name="buscar_resultados"),
]

AutoPedia/marcas/urls.py
# marcas/urls.py
from django.urls import path
from .views import ListaMarcas, DetalleMarca, crear_marca, editar_marca, eliminar_marca

app_name = "marcas"

urlpatterns = [
    path("lista_marcas/", ListaMarcas.as_view(), name="lista_marcas"),
    path("detalle_marca/<int:pk>/", DetalleMarca.as_view(), name="detalle_marca"),
    path("crear_marca/", crear_marca, name="crear_marca"),
    path("editar_marca/<int:pk>/", editar_marca, name="editar_marca"),
    path("eliminar_marca/<int:pk>/", eliminar_marca, name="eliminar_marca"),
]

AutoPedia/usuarios/urls.py
# usuarios/urls.py
from django.urls import path
from .views import registro, iniciar_sesion, cerrar_sesion

app_name = "usuarios"

urlpatterns = [
    path("registro/", registro, name="registro"),
    path("iniciar_sesion/", iniciar_sesion, name="iniciar_sesion"),
    path("cerrar_sesion/", cerrar_sesion, name="cerrar_sesion"),
]

AutoPedia/templates/base/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}AutoPedia{% endblock %}</title>
    {% load static %}

    <!--CSS-->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <!--Bootstrap CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>

    <!-- Header con colores personalizados -->
    <header class="py-2 bg-custom">
        <div class="container-fluid d-flex justify-content-between align-items-center">
            <a href="{% url 'home' %}" class="text-decoration-none text-dark d-flex align-items-center">
                <img src="{% static 'images/Logo1BG.png' %}" alt="Logo" width="60" height="54"
                    class="d-inline-block align-text-top me-2">
                <span class="fs-4 fw-bold text-light">AutoPedia</span>
            </a>

            <div>
                {% if user.is_authenticated %}
                <span class="text-light me-2">Bienvenido, {{ user.username }} </span>
                <a href="{% url 'usuarios:cerrar_sesion' %}" class="btn btn-outline-light">Cerrar Sesión</a>
                {% else %}
                <a href="{% url 'usuarios:iniciar_sesion' %}" class="btn btn-outline-light me-2">Iniciar Sesión</a>
                <a href="{% url 'usuarios:registro' %}" class="btn btn-outline-light">Registrarse</a>
                {% endif %}
            </div>
        </div>
    </header>




    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg custom-navbar-bg">
        <div class="container-fluid">
            <!-- Botón de colapso para dispositivos pequeños -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Contenido del Navbar -->
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'marcas:lista_marcas' %}">Marcas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'autos:lista_modelos' %}">Modelos</a>
                    </li>
                </ul>
                <form class="d-flex" action="{% url 'autos:buscar_resultados' %}" method="get">
                    <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>


    <!-- Contenido principal -->
    <div class="content">
        {% block content %}
        <!-- Contenido específico para cada plantilla -->
        {% endblock %}
    </div>

    <!-- Footer -->
    <footer class="bg-custom text-center py-3">
        <p>&copy; 2023 AutoPedia. Todos los derechos reservados.</p>
    </footer>

    <!--Bootstrap JS-->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>

</body>

</html>